name: render

permissions:
  contents: write

on:
  push:

jobs:
  export_svg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4       
      - run: |
          ls -l
          sudo apt-get update
          sudo apt-get -y install dvisvgm
          mkdir svg
          sudo dvisvgm --pdf --output=svg/implementations-shall.svg implementations-shall.pdf



  
